name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate contribution graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: aghelena
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout -B output
          git add output/*.svg
          git commit -m "update pacman graph" || echo "no changes"
          git push origin output
